#!/bin/bash
# This script converts a RFC 4716 SSH public key format inout file into the one-line format utilized by OpenSSH in key based authentication.
# See accompanying README for usage details
RFC4716key=$1
USERNAME=${2:-$USER}

# Check if keyfile exists
if [[ ! -f "$RFC4716key" ]];
  then
    echo "ERROR: Keyfile does not exist: $RFC4716key"
    exit 4
  else
    #Check if keyfile is RFC 4716 format
    ssh-keygen -if "$RFC4716key" &> /dev/null
    if [[ $? != 0 ]];
      then
        echo "ERROR: $RFC4716key is NOT a RFC 4716 keyfile."
        exit 8
      else
        id "$USERNAME" &> /dev/null
        if [[ $? != 0 ]];
          then
            echo "ERROR: Username not present on system: $USERNAME"
            exit 16
          else
            # Generates public key using ssh-keygen
            publickey=$(ssh-keygen -if "$RFC4716key")

            #Check if publickey is already present in users ~/.ssh/authorized_keys file
            duplicateKey_comment=$(grep "$publickey" "/home/$USERNAME/.ssh/authorized_keys" | sed 's_^.*==__' | sed 's_^\ __')
            if [[ ! -z $duplicateKey_comment ]];
              then
                echo "ERROR: Key is already present in $USERNAME's authorized_keys file"
                echo "  Existing key comment:"
                echo "    $duplicateKey_comment"
                echo "ERROR: NOT adding duplicate key to authorized_keys"
                exit 32
              else
                # Extracts comment from input publickey
                #   1. awk extracts muiltiline comment header
                #   2. sed removes trailing backslashes from comment header
                #   3. tr converts multiline comment into single line comment
                #   4. sed removes 'Comment: ' keyword and quotes
                comment=$(cat "$RFC4716key" | awk '/Comment:/,/[^\\]$/' | sed 's_\\$__' | tr -d '\n' | sed -e 's_Comment: __' -e 's_"__g')

                #Check if key comment is repeated
                repeatedComment_lines=$(grep "$comment" "/home/$USERNAME/.ssh/authorized_keys")
                if [[ ! -z $repeatedComment_lines ]];
                  then
                    echo "WARNING: Key(s) with similar comment is already present"
                    repeatedComment_count=1
                    echo "  New key comment: $comment"
                    # List the comments of the keys with similar comments
                    echo "$repeatedComment_lines" | while read commentLine; do
                      repeatedComment_comment=$(echo $commentLine | sed 's_^.*==__' | sed 's_^\ __' )
                      echo "  Similar Key Comment $repeatedComment_count : $repeatedComment_comment"
                      ((repeatedComment_count))
                    done
                fi

                comment="$comment ADDED on: $(date)"
                comment="$comment ADDED by: $USER"

                # Concatenates the publickey and comment
                openssh="$publickey $comment"

                # Creates user's .ssh directory if not present
                mkdir -p "/home/$USERNAME/.ssh/"

                # Enable write permissions to users  authorized_keys file
                touch "/home/$USERNAME/.ssh/authorized_keys"
                chmod 660 "/home/$USERNAME/.ssh/authorized_keys"

                # Appends extracted key w. comment to users authorized_keys file
                #  to the end of the file, leaving existing keys untouched
                echo $openssh >> "/home/$USERNAME/.ssh/authorized_keys"

                # Fix file/folder permissions, or else sshd will not accept authorized_keys file
                chmod go-w "/home/$USERNAME"
                chmod go-rwx "/home/$USERNAME/.ssh"
                chmod 600 "/home/$USERNAME/.ssh/authorized_keys"
                chown --quiet "$USERNAME" "/home/$USERNAME"
                chown --quiet --recursive "$USERNAME" "/home/$USERNAME/.ssh"


                echo "SUCCESS: Added public key to authorized_keys file"
                echo "Username: $USERNAME"
                echo "Keyfile:  $RFC4716key"
                echo "Comment:  $comment"
            fi
        fi
    fi
fi
